### PR TITLE
Parse params in script

### PR DESCRIPTION
**Pull request by AlexAxthelm**
- Parse parameters in calling script, and pass to function, rather than parse arguments inside a function
- Export manifest when creating a report
- Use the new parameters schema (array of filenames, not single string)

### CODE REVIEW

**Comment by jdhoffa** [comment]
Can you please open a separate PR for the "Use new RMI blob upload action to upload test results to blob store" commit please? 

That feels rather separate from this PR logically (has little to do with moving parse params around)

**Comment by AlexAxthelm** [comment]
> Can you please open a separate PR for the "Use new RMI blob upload action to upload test results to blob store" commit please?
> 
> That feels rather separate from this PR logically (has little to do with moving parse params around)

Please see https://github.com/RMI-PACTA/workflow.pacta.report/pull/31, which copies the relevant files. Leaving them here as well, as they are necessary for passing checks (but won't be a "change" once that PR is merged)

**Comment by AlexAxthelm** [comment]
@jdhoffa Can I get an approval here too?

**Review by jdhoffa — APPROVED** [review]
LGTM

**Pull request merged**
